version: '3.9'
services:
  database:
    image:  mongo:4.2.3-bionic
    container_name: mongo_db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=netflix
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./database:/usr/src/db
  backend:
    container_name: backend
    build: ./server
    depends_on:
      - database
    volumes:
      - ./server:/usr/src/app
    environment:
      PORT: 8080
      MONGO_URI: mongodb://database:27017/netflix
  frontend:
    container_name: frontend
    build: ./client
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
    environment:
      PORT: 3000
    ports:
      - 3000:3000